export const LOCAL_STORAGE_OPTIMISM_CHAIN_ID_KEY = '__OPTIMISM_CHAIN_ID__'
export const LOCAL_STORAGE_ANNOUNCEMENTS_KEY = '__ANNOUNCEMENTS_KEY__'
export const LOCAL_STORAGE_TERMS_OF_USE_KEY = '__TERMS_OF_USE_KEY__'
export const LOCAL_STORAGE_TRADER_SETTINGS_KEY = '__LOCAL_STORAGE_TRADE_SETTINGS_KEY__'
