/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CamelotNitroPool,
  CamelotNitroPoolInterface,
} from "../CamelotNitroPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "totalDepositAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardDebtToken1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardDebtToken2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pendingRewardsToken1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pendingRewardsToken2",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CamelotNitroPool__factory {
  static readonly abi = _abi;
  static createInterface(): CamelotNitroPoolInterface {
    return new utils.Interface(_abi) as CamelotNitroPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CamelotNitroPool {
    return new Contract(address, _abi, signerOrProvider) as CamelotNitroPool;
  }
}
