/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { CamelotPool, CamelotPoolInterface } from "../CamelotPool";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CamelotPool__factory {
  static readonly abi = _abi;
  static createInterface(): CamelotPoolInterface {
    return new utils.Interface(_abi) as CamelotPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CamelotPool {
    return new Contract(address, _abi, signerOrProvider) as CamelotPool;
  }
}
