/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { TransferEth, TransferEthInterface } from "../TransferEth";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "destination",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferEth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TransferEth__factory {
  static readonly abi = _abi;
  static createInterface(): TransferEthInterface {
    return new utils.Interface(_abi) as TransferEthInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TransferEth {
    return new Contract(address, _abi, signerOrProvider) as TransferEth;
  }
}
