/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VelodromeStaking,
  VelodromeStakingInterface,
} from "../VelodromeStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "rewardRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class VelodromeStaking__factory {
  static readonly abi = _abi;
  static createInterface(): VelodromeStakingInterface {
    return new utils.Interface(_abi) as VelodromeStakingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VelodromeStaking {
    return new Contract(address, _abi, signerOrProvider) as VelodromeStaking;
  }
}
