export const DESKTOP_HEADER_NAV_HEIGHT = 56
export const DESTKOP_HEADER_NOTICE_HEIGHT = 32
export const MOBILE_FOOTER_HEIGHT = 72
export const MOBILE_HEADER_HEIGHT = 42
export const DESKTOP_RIGHT_COLUMN_WIDTH = 360

export const DESKTOP_LAYOUT_LARGE_WIDTH = 1420
export const DESKTOP_LAYOUT_WIDTH = 1080

export const PORTFOLIO_CARD_HEIGHT = [280, 350]
export const VAULTS_CHART_HEIGHT = [120, 260]
export const VAULTS_INDEX_CHART_HEIGHT = [120, 200]
export const FAUCET_MODAL_WIDTH = 450

export const TRADE_BOARD_MIN_HEIGHT = [450, 300]

export const ONBOARDING_MODAL_WIDTH = 600

export const MIN_TRADE_CARD_HEIGHT = 400
